-- local dap, dapui = require("dap"), require("dapui")
--
-- require("mason-nvim-dap").setup({
--   automatic_installation = true,
--   automatic_setup = true,
-- })
-- require('telescope').load_extension('dap')
--
--
-- dap.adapters.coreclr = {
--   type = 'executable',
--   command = 'netcoredbg',
--   args = { '--interpreter=vscode' }
-- }
--
--
-- dap.configurations.cs = {
--   {
--     type = "coreclr",
--     name = "launch - netcoredbg",
--     request = "launch",
--     env = {
--       ASPNETCORE_ENVIRONMENT = "Development",
--       NVIM_TEST = "Test from dap file"
--     },
--     program = function()
--       return vim.fn.input('Path to dll', vim.fn.getcwd() .. '/bin/Debug/', 'file')
--     end,
--   },
-- }
--
--
--
-- dap.configurations.javascript = {
--   {
--     name = 'Launch',
--     type = 'node2',
--     request = 'launch',
--     program = '${file}',
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = 'inspector',
--     console = 'integratedTerminal',
--   },
--   {
--     -- For this to work you need to make sure the node process is started with the `--inspect` flag.
--     name = 'Attach to process',
--     type = 'node2',
--     request = 'attach',
--     processId = require 'dap.utils'.pick_process,
--   },
-- }
-- dap.configurations.javascriptreact = { -- change this to javascript if needed
--   {
--     type = "chrome",
--     request = "attach",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 9222,
--     webRoot = "${workspaceFolder}"
--   }
-- }
--
-- dap.configurations.typescriptreact = { -- change to typescript if needed
--   {
--     type = "chrome",
--     request = "attach",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 9222,
--     webRoot = "${workspaceFolder}"
--   }
-- }
--
--
-- dap.configurations.sh = {
--   {
--     type = 'bashdb';
--     request = 'launch';
--     name = "Launch file";
--     showDebugOutput = true;
--     pathBashdb = vim.fn.stdpath("data") .. '/mason/packages/bash-debug-adapter/extension/bashdb_dir/bashdb';
--     pathBashdbLib = vim.fn.stdpath("data") .. '/mason/packages/bash-debug-adapter/extension/bashdb_dir';
--     trace = true;
--     file = "${file}";
--     program = "${file}";
--     cwd = '${workspaceFolder}';
--     pathCat = "cat";
--     pathBash = "/bin/bash";
--     pathMkfifo = "mkfifo";
--     pathPkill = "pkill";
--     args = {};
--     env = {};
--     terminalKind = "integrated";
--   }
-- }
--
--
--
--
-- dapui.setup()
--
-- dap.listeners.after.event_initialized["dapui_config"] = function()
--   dapui.open()
-- end
-- dap.listeners.before.event_terminated["dapui_config"] = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_exited["dapui_config"] = function()
--   dapui.close()
-- end
return {
}
